export const API_ENDPOINTS = {
  getAboutUs: "/website/aboutUs",
  getContactInfos: "/website/contactInfos",
  getGallery: "/website/v2/gallery",
  getServices: "/website/services",
  getEvents: "/website/events?",
  getClients: "/website/clients",
  getPrivacyPolicy: "/website/privacyPolicy",
  getTermsConditions: "/website/termsConditions",
  getCities: "/cities",
  getDepartments: "/departments/users",
  getWorkTypes: "/workTypes",
  registerJobSeeker: "/jobSeekers/regsiter",
  sendTechSupportMessage: "/techSupport/create",
  confirmEmail: "/auth/confirmEmail",
  getJobs: "/website/jobs",
  sendCompanyApplication: "/website/company-application",
  getContract: (contractId: string) => `/website/contract/${contractId}`,
  signContract: "/website/sign-contract",
  getContractTemplate: "/website/get-contract-template",
  getContractFont: "/website/get-contract-font",
  getRatingQuestions: (userId: number) =>
    `/rating/get-user-questions?userId=${userId}`,
  submitRating: "/rating/submit",
  getProjects: "/website/v2/projects?",
  getProject: (projectId: string) => `/website/v2/projects/${projectId}`,
  getUpcomingProjects: "/website/v2/projects/upcoming?",
  verifyEmail: "/website/verify_email",
  verifyOtp: "/website/verify_otp",
  uploadFreelancerIntroVideo: "/website/upload_freelancer_intro_video",

  businessRegistration: "/clients/register",
};
